// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auubdfjgylugyircgkxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dWJkZmpneWx1Z3lpcmNna3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDUyNDIsImV4cCI6MjA2NTU4MTI0Mn0.aX5xFMkENewAfmEH96_oyPfobGTSTHZk0TKEE87SRzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);